<?php
// $Id$

/**
 * Implementation of hook_perm().
 */

function spjgaji_permission() {
  return array(
    'spp gaji permission' => array(
      'title' => t('spp gaji permission'),
      'description' => t('spp gaji permission'),
    ),
  );
}
/**
 * Implementation of hook_menu().
 */

function spjgaji_menu() {

	$items['spjgaji/baru'] = array (
      'title' => 'SPJ Gaji | Pilih SP2D',
	  'description' => 'SPJ Gaji | Pilih SP2D',
	  //'title callback' => 'spjgaji_title_callback',	  
      'page callback' => 'spjgaji_newpick_main',
      //'access arguments' => array ('access content'),
	  'access arguments' => array ('spp gaji permission'),
	  //'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'spjgaji_newpick_main.php',
      'type' => MENU_NORMAL_ITEM,
    );

	$items['spjgaji/barupost'] = array (
      'title' => 'SPJ Gaji | Baru',
	  'description' => 'SPJ Gaji | Baru',
	  //'title callback' => 'spjgaji_title_callback',	  
      'page callback' => 'spjgaji_newpost_main',
      'access arguments' => array ('spp gaji permission'),
	  //'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'spjgaji_newpost_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
	
	$items['spjgaji/edit'] = array (
      'title' => 'SPJ Gaji',
	  'description' => 'SPJ Gaji',
	  //'title callback' => 'spjgaji_title_callback',	  
      'page callback' => 'spjgaji_edit_main',
      'access arguments' => array ('spp gaji permission'),
	  //'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'spjgaji_edit_main.php',
      'type' => MENU_NORMAL_ITEM,
    );

    $items['spjgaji/delete'] = array (
      'title' => 'Hapus SPJ Gaji',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('spjgaji_delete_form'),
      //'access arguments' => array ('desa penghapusan'),
	  'access arguments' => array ('spp gaji permission'),
      'file' => 'spjgaji_delete_form.php',
      'type' => MENU_CALLBACK,
    );	


    return $items;
}

