<?php
// $Id$

/**
 * Implementation of hook_perm().
 */
//onModuleCreationWizard
function spjls_perm() {
    return array(
        'access penata content',
		'access laporan penata'
	);
}

/**
 * Implementation of hook_menu().
 */

function spjls_menu() {
	$items['spjls/baru'] = array (
      'title' => 'SPJ LS | Pilih SP2D',
	  'description' => 'SPJ LS | Pilih SP2D',
	  //'title callback' => 'spjls_title_callback',	  
      'page callback' => 'spjls_newpick_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'spjls_newpick_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
	$items['spjls/barupost'] = array (
      'title' => 'SPJ Gaji | Baru',
	  'description' => 'SPJ Gaji | Baru',
	  //'title callback' => 'spjgaji_title_callback',	  
      'page callback' => 'spjls_newpost_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'spjls_newpost_main.php',
      'type' => MENU_NORMAL_ITEM,
    );
	
	$items['spjls/edit'] = array (
      'title' => 'SPJ LS',
	  'description' => 'SPJ LS',
	  //'title callback' => 'spjls_title_callback',	  
      'page callback' => 'spjls_edit_main',
      //'access arguments' => array ('access content'),
	  'access callback' => 'user_is_logged_in',
      'weight' => 11,
      'file' => 'spjls_edit_main.php',
      'type' => MENU_NORMAL_ITEM,
    );

    $items['spjls/delete'] = array (
      'title' => 'Hapus SPJ LS',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('spjls_delete_form'),
      //'access arguments' => array ('desa penghapusan'),
	  'access arguments' => array ('access content'),
      'file' => 'spjls_delete_form.php',
      'type' => MENU_CALLBACK,
    );	


    return $items;
}

